# 預處理配置
input_dir: "data/raw"
output_dir: "data/processed"

segmentation:
  min_duration: 0.5
  max_duration: 5.0
  top_db: 20

denoising:
  apply_bandpass: true
  lowcut: 500
  highcut: 4000
  apply_spectral_subtraction: false

normalization:
  normalize_amplitude: true
  target_dBFS: -20
  apply_pre_emphasis: true
  pre_emphasis_coef: 0.97
